eom-tool: Switch to kernel_headers for UAPI includes
Replaced deprecated KERNEL_OBJ references in
eom_tool Android.mk with LOCAL_HEADER_LIBRARIES := qti_kernel_headers.
This aligns with the new build system requirements and removes
following kernel_obj_errors warnings during build.

kernel_obj_error : 1
Error: Using kernel_obj_errors in below makefiles. This will be deprecated soon, please remove.
vendor/qcom/opensource/coretech-tools/eom_tool/Android.mk

Change-Id: Id0111416afc7c90b74f62c43b9eb1cd4514b7697
Signed-off-by: Arnav Kumar Dawn <arnavkum@qti.qualcomm.com>